### ISSUE TITLE
Blacklisted file extensions are still accepted

### ISSUE THREAD

**Issue by ghost** [xatasan/registrars#1]
As the title says, uploading a blacklisted file extension (exe, msi, bat, etc.) gives a 403 but a link to download the file anyways.

![2018-02-24_15-35-07](https://user-images.githubusercontent.com/14350932/36636277-74c098de-1978-11e8-9b78-2a080a25514e.png)

**Comment by xatasan** [comment]
Ok, that must have slipped through as I rewrote the upload system. Will try and fix it as soon as I get around to it.
